Homework6
akuzmichova/Spring2021_SeleniumCucumber pull request #3
Opened 2021-06-03 03:05 UTC by akuzmichova

Hi Deepak, can you please review

2021-06-04 19:10 UTC, deepaktechnosoft requested changes

2021-06-04 19:10 UTC, deepaktechnosoft commented on src/test/java/Pages/Darksky/Homepage.java
> +    public List<String> getTimeLineFromCalendar() {
Good code. My suggestion would be to move it in the Utils class.
As it is not an action or data user getting from WebPage.

2021-06-04 19:10 UTC, deepaktechnosoft commented on src/test/java/Pages/Facebook/HomepageFB.java
> +    By genderRadioButtons = By.className("_8esa");
use better locator, class name looks random data

2021-06-04 19:10 UTC, deepaktechnosoft commented on src/test/java/Pages/Facebook/HomepageFB.java
> +            isGenderRadioButtonSelected &= isElementSelected(genderRadioButton);
I think, you should use OR operator instead AND.
bcz, even if all radio buttons are selected, you will have 'false' in isGenderRadioButtonSelected

2021-06-04 19:10 UTC, deepaktechnosoft commented on src/test/java/StepDefinition/Facebook/MessengerSD.java
> +        mes.switchToMessengerLoginHandle();
does it open a new window??

2021-06-07 01:54 UTC, akuzmichova commented on src/test/java/StepDefinition/Facebook/MessengerSD.java
> +        mes.switchToMessengerLoginHandle();
Hi, yes, it is opening new window

2021-06-07 01:55 UTC, akuzmichova commented on src/test/java/Pages/Facebook/HomepageFB.java
> +            isGenderRadioButtonSelected &= isElementSelected(genderRadioButton);
Agree

2021-06-07 01:56 UTC, akuzmichova commented on src/test/java/Pages/Facebook/HomepageFB.java
> +    By genderRadioButtons = By.className("_8esa");
changed to By.xpath("//input[@type='radio']");

2021-06-07 13:48 UTC, deepaktechnosoft approved these changes

2021-06-07 13:48 UTC, merged